# NON GRADED CHALLENGE 5

In [34]:
# Import Library
import numpy as np
from numpy import array
from numpy.linalg import inv
from numpy.linalg import det

## 1. Buatlah Tensor dibawah ini dengan Python:

[[23 50 7 12] [57 67 99 43] [75 21 57 12] [87 26 18 84]]

In [2]:
Tensor = np.array([[23,50,7,12],[57,67,99,43],[75,21,57,12],[87,26,18,84]])

In [3]:
Tensor

array([[23, 50,  7, 12],
       [57, 67, 99, 43],
       [75, 21, 57, 12],
       [87, 26, 18, 84]])

In [4]:
Tensor.shape

(4, 4)

## 2. Lakukan perkalian terhadap matrix berikut :

A = [23 50 19 7 12 109 57 67 98]
B = [17 22 19]

In [20]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([17,22,19])

In [16]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [21]:
B

array([17, 22, 19])

In [19]:
print('A x B : \n', A @ B)

A x B : 
 [1852 2454 4305]


## 3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini: 

A = [[23,50,19],[7,12,109],[57,67,98]]

In [36]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])

In [38]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [39]:
transpose = A.T
determinant = det(A)
invert    = inv(A)
print('TRANSPOSE MATRIX: \n',transpose)
print('')
print('DETERMINANT MATRIX: \n',determinant)
print('')
print('INVERT MATRIX: \n',invert)

TRANSPOSE MATRIX: 
 [[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]

DETERMINANT MATRIX: 
 131344.0000000002

INVERT MATRIX: 
 [[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
